services:
    app:
        build: .
        depends_on:
            - database
        volumes:
            - /app/node_modules
            - ./logs:/app/logs
            - ./static/uploads:/app/static/uploads
        env_file:
            - .env
        ports:
            - 3000:3000
    database:
        image: mysql:8.4
        volumes:
            - ./database/init/:/docker-entrypoint-initdb.d/:ro
            - ./database/data:/var/lib/mysql
        env_file:
            - .env
        expose:
            - 3306
    scraper_worker:
        build: .
        profiles:
            - manual
        command: ["node", "/app/dist/scraper_worker.js"]
        depends_on:
            - database
        volumes:
            - /app/node_modules
            - ./logs:/app/logs
        env_file:
            - .env
