networks:
    app-net:
        driver: bridge
services:
    app:
        build: .
        command: ["npm", "run", "start"]
        depends_on:
            - database
        volumes:
            - /app/node_modules
        env_file:
            - .env
        ports:
            - 3000:3000
        networks:
            - app-net
    database:
        image: mysql:latest
        volumes:
            - ./database/init/:/docker-entrypoint-initdb.d/:ro
            - ./database/data:/var/lib/mysql
        env_file:
            - .env
        expose:
            - 3306
        networks:
            - app-net
