# services:
#     app:
#         command: ["npm", "run", "dev"]
#         depends_on:
#             - database
#         volumes:
#             - .:/app
#             - /app/node_modules
#     database:
#         ports:
#             - 3306:3306
